### ISSUE TITLE
Simplify CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [lilyminbiole/prj-rev-bwfs-dasmoto#5]
It is best to try to simplify the CSS code as much as possible. This will make the code cleaner and remove repetition. 

Since you applied the font-family property to html, all elements in the html tag will also inherit this property, so you can remove the property from the other selectors. In addition, the font-weight property can also be applied to multiple elements like so

```css
html {
  font-family: Helvetica;
  font-weight: bold;
}
```
